/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */
package org.opensearch.securityanalytics.commons.factory;

import com.google.common.collect.HashBasedTable;
import com.google.common.collect.Table;

/**
 * A generic helper class to cache the results of previously constructed objects. Factory implementations can extend this
 * class to automatically provided a cached factory implementation.
 *
 * @param <T> - The class of the first input parameter used to generate an object
 * @param <U> - The class of the second input parameter used to generate an object
 * @param <V> - The class of the objects generated by the factory
 */
public abstract class BinaryParameterCachingFactory<T, U, V> {
    private final Table<T, U, V> cache;

    public BinaryParameterCachingFactory() {
        this.cache = HashBasedTable.create();
    }

    protected abstract V doCreate(T parameter1, U parameter2);

    public V create(final T parameter1, final U parameter2) {
        if (!cache.contains(parameter1, parameter2)) {
            cache.put(parameter1, parameter2, doCreate(parameter1, parameter2));
        }

        return cache.get(parameter1, parameter2);
    }
}
