/*
 * Copyright OpenSearch Contributors
 * SPDX-License-Identifier: Apache-2.0
 */
package org.opensearch.securityanalytics.commons.factory;

import com.google.common.cache.Cache;
import com.google.common.cache.CacheBuilder;

/**
 * A generic helper class to cache the results of previously constructed objects. Factory implementations can extend this
 * class to automatically provided a cached factory implementation.
 *
 * @param <T> - The class of the input parameter used to generate an object
 * @param <U> - The class of the objects generated by the factory
 */
public abstract class UnaryParameterCachingFactory<T, U> {
    private final Cache<T, U> cache;

    public UnaryParameterCachingFactory() {
        this.cache = CacheBuilder.newBuilder().build();
    }

    protected abstract U doCreate(T parameter);

    public U create(T parameter) {
        if (cache.getIfPresent(parameter) == null) {
            cache.put(parameter, doCreate(parameter));
        }

        return cache.getIfPresent(parameter);
    }
}
